version: '3.8'

services:
  # PostgreSQL Database for Production
  postgres-db:
    container_name: timescaledb_prod_container
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cogniprice_db
    volumes:
      - timescale_data:/var/lib/postgresql/data  # Persist data for production
    profiles:
      - prod

  # PostgreSQL Database for Testing
  postgres-db-test:
    container_name: timescaledb_test_container
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - "5433:5432"  # Expose different port for the test database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cogniprice_db_test  # Use a different test database
    volumes:
      - /tmp/test-db-data:/var/lib/postgresql/data  # Non-persistent, temp data
    profiles:
      - test  # This service will only start when the 'test' profile is activated

  # Zookeeper
  zookeeper:
    container_name: zookeeper-1
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

      # Kafka
  kafka:
    container_name: kafka-1
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  timescale_data:
